### ISSUE TITLE
getting "table:" message in the chat after any loading screen

### ISSUE THREAD

**Issue by DarkLCF** [masomh-personal/ElvUI_mhTags#3]
![WoWScrnShot_112724_231226](https://github.com/user-attachments/assets/2358aad1-6afa-4b07-a253-5be79d10cb33)

This is with elvui 13.81, and the 3.0.0 release of this addon, doesn't happen with the 2.0.3 release

**Comment by masomh-personal** [comment]
Hey there Dark. Interesting. You said you are on the latest release. I will check this out tonight.

**Comment by masomh-personal** [comment]
Yep, I'm an idiot and forgot to remove a debugging line of code. Fixing it now and getting it set up for release. Check for it in your curse updater.
